! ANALYSIS ALGORITHM
! DATE WRITTEN: DECEMBER 24, 2019
! DATE UPDATED: OCTOBER 25, 2022
! PURPOSE: converts report files to GNUPLOT view-ready files

! #######################################################################################################
!
! [ HOW TO USE]
!
! 1. Make sure that fort.10 and the cleaned trajectory file is present in current working directory
!
! 2. fort files generated by cluster_nm.f should be present in current working directory
!
! 3. Set desired parameter settings in fort.10
!         (settings during cluster analysis should be retained)
!
! 4. Compile algorithm
!          gfortran -o3 graphing.f -o graphing
!
! 5. Begin graphing
!          ./graphing < (cleaned trajectory file)
!
! 6. Activate GNU scripts
!          ./(name of GNU script)
!
! ########################################################################################################
!
! [ SECTIONS ]
!
! VII. REFORMATTING REPORT FILES FOR GNUPLOT
!
! VII.A. DETERMINING SYSTEM SIZE!
! VII.B. READING REPORT FILES
! VII.C. WRITING REFORMATTED FILES
!
! VIII. GENERATING GNU FILES TO PLOT REPORTS
!
! VIII.A.1. SAVING IMPORTANT DETAILS!
! VIII.A.2 DETERMINE INVOLVED MOLECULES
!
! VIII.B.1. RADIAL DENSITY PROFILE #1A - SPECIFYING PARAMETERS
! VIII.B.2. RADIAL DENSITY PROFILE #1A - GENERATE GNU FILE
!
! VIII.C.1. RADIAL DENSITY PROFILE #1B - SPECIFYING PARAMETERS
! VIII.C.2. RADIAL DENSITY PROFILE #1B - GENERATE GNU FILE
!
! VIII.D.1. RADIAL DENSITY PROFILE #2A - SPECIFYING PARAMETERS
! VIII.D.2. RADIAL DENSITY PROFILE #2A - GENERATE GNU FILE
!
! VIII.E.1. RADIAL DENSITY PROFILE #2B - SPECIFYING PARAMETERS
! VIII.E.2. RADIAL DENSITY PROFILE #2B - GENERATE GNU FILE
!
! VIII.F.1. RADIAL DENSITY PROFILE #3A - SPECIFYING PARAMETERS
! VIII.F.2. RADIAL DENSITY PROFILE #3A - GENERATE GNU FILE
!
! VIII.G.1. RADIAL DENSITY PROFILE #3B - SPECIFYING PARAMETERS
! VIII.G.2. RADIAL DENSITY PROFILE #3B - GENERATE GNU FILE
!
! VIII.H.1. RADIAL DISTRIBUTION FUNCTION #1A - SPECIFYING PARAMETERS
! VIII.H.2. RADIAL DISTRIBUTION FUNCTION #1A - GENERATE GNU FILE
!
! VIII.I.1. RADIAL DISTRIBUTION FUNCTION #1B - SPECIFYING PARAMETERS
! VIII.I.2. RADIAL DISTRIBUTION FUNCTION #1B - GENERATE GNU FILE
!
! VIII.J.1. CLUSTER SIZE FREQUENCY - SPECIFYING PARAMETERS
! VIII.J.2. CLUSTER SIZE FREQUENCY - GENERATE GNU FILE
!
! VIII.K.1. MOLE FRACTION - SPECIFYING PARAMETERS
! VIII.K.2. MOLE FRACTION - GENERATE GNU FILE
!
! VIII.L.1. CLUSTER MASS - SPECIFYING PARAMETERS
! VIII.L.2. CLUSTER MASS - GENERATE GNU FILE
!
! VIII.M.1. CLUSTER MASS UPPER LIMIT - SPECIFYING PARAMETERS
! VIII.M.2. CLUSTER MASS UPPER LIMIT - GENERATE GNU FILE
!
! VIII.N.1. CLUSTER MASS LOWER LIMIT - SPECIFYING PARAMETERS
! VIII.N.2. CLUSTER MASS LOWER LIMIT - GENERATE GNU FILE
!
! VIII.O.1. CLUSTER RADIUS - SPECIFYING PARAMETERS
! VIII.O.2. CLUSTER RADIUS - GENERATE GNU FILE
!
! ########################################################################################################

 	program graphing

! [ USER-DEFINED VARIABLES ]

	implicit none
	integer eek,dd,jj,pp,v,trcnv,ca,uu,nn
	integer l,mq,idm,ppi,ski,np
	integer mim,mfm,tc,pop,nth
	integer rmd,mxv,rmc,nfn,nin,ffmmi,ffmmf
	integer val0(1:60000)
	integer gmin(1:20,1:20),gmax(1:20,1:20)
	integer le(1:20),col(1:5),fmol(1:5),temp2,temp4,t1,t2
	integer col2(1:5),col3(1:5),temp7,temp8
	integer clock_rate,clock_max
	integer RPSF,RPMOF,RPM,RPR,RPNR,RPCS,RPS,RPTR 
	integer RPRD1,RPRD2,RPRD3,RDF 
	double precision yy,a,cb,cc,cd,ce,cf,cg,ch,ci,ts,tim,bb,qq,qr
	double precision cj,ck,cl
	double precision SECONDS 
	double precision time(1:60000),val1(1:60000),val2(1:60000)
	double precision val3(1:60000),val4(1:60000),val5(1:60000)
	double precision val6(1:60000),val7(1:60000),val8(1:60000)
	double precision val9(1:60000),val10(1:60000)
	double precision val11(1:60000)
	double precision plne(1:60000),molty(1:10),mers(1:60000)
	double precision gt(1:20)
	character(len=3) qb,nam(1:5),temp1
	character(len=9) clr(1:5),temp6
	character(len=11) sa08,sa09
	character(len=13) sa24
	character(len=14) sa05
	character(len=15) sa22,sa06,saF6
	character(len=16) sa07
	character(len=18) filea
	character(len=19) sa32
	character(len=20) spwa
	character(len=20) sa12,sa52,sa62,sa72
	character(len=22) sa01,saF1,sa11,sa21,sa31,sa51,sa61,sa71
	character(len=23) spca,spwb,spwc
	character(len=26) sa23,spcb,spcc
	character(len=28) sam(1:10),temp3,sub(1:10),temp5
	character(len=29) sa04
	character(len=30) saF3
	character(len=31) sa02
	character(len=33) saF2
	character(len=34) sa03
	character(len=39) saF4
	character(len=41) rdpxrange,rdpxtics,freyrange,freytics,mascbrange
	character(len=41) mascbtics,radcbrange,genylabelof,genclabelof
	character(len=41) genxrange,genyrange,genxtics,genytics
	character(len=42) saR4
 	logical GENERATE
 	
	call system_clock (t1, clock_rate, clock_max)

	write(*,*) "   [3.A] (BRANCH TASK: graphing.f)"
	write(*,*) " "

!-------VII. REFORMATTING REPORT FILES FOR GNUPLOT

!	    write(*,*) "####################################"
!	    write(*,*) "#                                  #"
!	    write(*,*) "#    REFORMATTING REPORT FILES     #"
!	    write(*,*) "#                                  #"
!	    write(*,*) "####################################"
      
!-------VII.A. DETERMINING SYSTEM SIZE

	read(10,*) 
	read(10,*) ffmmi,ffmmf
	read(10,*) 
	read(10,*) 
	read(10,*) trcnv
	read(10,*) pop
	do ski = 1,58
	 read( 10,* ) 
	enddo
	read(10,*) RPRD1
	read(10,*) RPRD2
	read(10,*) RPRD3
	read(10,*) RDF
	read(10,*) RPSF
	read(10,*) RPMOF
	read(10,*) RPM
	read(10,*) RPR
	read(10,*) RPNR
	read(10,*) RPCS
	read(10,*) RPS
	read(10,*) RPTR

	if ( trcnv.eq. 500 ) then 
	 jj=250        !needs manual adjustment
	 pp=3
	else
	 jj=50         !needs manual adjustment
	 pp=7
	endif 
	 uu=(pop/jj)*2
	 yy=(DBLE(trcnv)/1000d0)

!-------VII.B. READING REPORT FILES

	spca='(i1,f22.17,f12.1,i16)'
	spcb='(i1,f22.17,f12.1,f22.17)'
	spcc='(i1,f22.17,f12.1,f50.35)'
	
	spwa='(f22.17,f12.1,i16)'
	spwb='(f22.17,f12.1,f25.18)'
	spwc='(f22.17,f12.1,f50.35)'
	
	qq = 1d0 - (1d-5)
	qr = 1d0 + (1d-5)

	if ( RPSF .eq. 1 ) then 
	read( 3120,spca )   !Size (10^2) frequency
	endif
	
	if ( RPMOF .eq. 1 ) then
	read( 3220,spcb )   !mole frac water
	read( 3221,spcb )   !mole frac nonane
	read( 3222,spcb )   !mole frac butanol
	read( 3223,spcb )   !mole frac ammonia
	read( 3224,spcb )   !mole frac methanol
	read( 3225,spcb )   !mole frac acetic acid
	read( 3226,spcb )   !mole frac octanol
	endif 
	
	if ( RPM .eq. 1 ) then
	read( 3320,spcc )   !mass
	read( 3321,spcc )   !mass fraction, upper
	read( 3322,spcc )   !mass fraction, lower
	endif 
	
	if ( RPR .eq. 1 ) then
	read( 3420,spcb )   !radius
	endif
	
	do eek=1,100
	 do dd=1,uu
	    
	  if ( RPSF .eq. 1 ) then
	  read( 3120,spca ) v,a,bb,ca  !Size (10^2) frequency
	  val0(dd) = ca
	  endif 
	
	  if ( RPMOF .eq. 1 ) then
	  read( 3220,spcb ) v,a,bb,cb  !mole frac water
	  read( 3221,spcb ) v,a,bb,cc  !mole frac nonane
	  read( 3222,spcb ) v,a,bb,cd  !mole frac butanol
	  read( 3223,spcb ) v,a,bb,ce  !mole frac ammonia
	  read( 3224,spcb ) v,a,bb,cj  !mole frac methanol
	  read( 3225,spcb ) v,a,bb,ck  !mole frac acetic acid
	  read( 3226,spcb ) v,a,bb,cl  !mole frac octanol
	  val1(dd) = cb
	  val2(dd) = cc
	  val3(dd) = cd
	  val4(dd) = ce
	  val9(dd) = cj
	  val10(dd) = ck
	  val11(dd) = cl
	  endif 
	
	  if ( RPM .eq. 1 ) then 
	  read( 3320,spcc ) v,a,bb,cf  !mass
	  read( 3321,spcc ) v,a,bb,cg  !mass fraction, upper
	  read( 3322,spcc ) v,a,bb,ch  !mass fraction, lower
	  val5(dd) = cf
	  val6(dd) = cg
	  val7(dd) = ch
	  endif     
	
	  if ( RPR .eq. 1 ) then
	  read( 3420,spcb ) v,a,bb,ci  !radius
	  val8(dd) = ci
	  endif
	  
	  if ( ( RPSF  .eq. 1 ) 
     &    .or. ( RPSF  .eq. 1 ) 
     &    .or. ( RPMOF .eq. 1 )
     &    .or. ( RPM   .eq. 1 )  
     &    .or. ( RPR   .eq. 1 ) ) then
	  time(dd) = a                      
	  mers(dd) = bb
	  plne(dd) = a-yy
   	  endif
 	  
 	  if ( RPMOF .eq. 1 ) then
 	  if (( val1(dd) .gt. qq ) .and. ( val1(dd) .lt. qr )) then
 	     val1(dd) = 0.998999999999999999
 	  endif
 	  if (( val2(dd) .gt. qq ) .and. ( val2(dd) .lt. qr )) then
 	     val2(dd) = 0.998999999999999999
 	  endif
 	  if (( val3(dd) .gt. qq ) .and. ( val3(dd) .lt. qr )) then
 	     val3(dd) = 0.998999999999999999
 	  endif
 	  if (( val4(dd) .gt. qq ) .and. ( val4(dd) .lt. qr )) then
 	     val4(dd) = 0.998999999999999999
 	  endif
 	  if (( val9(dd) .gt. qq ) .and. ( val9(dd) .lt. qr )) then
 	     val9(dd) = 0.998999999999999999
 	  endif
 	  if (( val10(dd) .gt. qq ) .and. ( val10(dd) .lt. qr )) then
 	     val10(dd) = 0.998999999999999999
 	  endif
 	  if (( val11(dd) .gt. qq ) .and. ( val11(dd) .lt. qr )) then
 	     val10(dd) = 0.998999999999999999
 	  endif
 	  endif
 	  if (RPM .eq. 1) then   
 	  if (( val6(dd) .gt. qq ) .and. ( val6(dd) .lt. qr )) then
 	     val6(dd) = 0.998999999999999999
 	  endif
 	  endif
 	 enddo

!-------VII.C. WRITING REFORMATTED FILES

	 do dd = 1,uu
	  if ( RPSF .eq. 1 ) then
	  write( 4120,spwa ) plne(dd),mers(dd),val0(dd)
	  endif
	
	  if ( RPMOF .eq. 1 ) then
	  write( 4220,spwb ) plne(dd),mers(dd),val1(dd)
	  write( 4221,spwb ) plne(dd),mers(dd),val2(dd)
	  write( 4222,spwb ) plne(dd),mers(dd),val3(dd)
	  write( 4223,spwb ) plne(dd),mers(dd),val4(dd)
	  write( 4224,spwb ) plne(dd),mers(dd),val9(dd)
	  write( 4225,spwb ) plne(dd),mers(dd),val10(dd)
	  write( 4226,spwb ) plne(dd),mers(dd),val11(dd)
	  endif
	
	  if ( RPM .eq. 1 ) then
	  write( 4320,spwc ) plne(dd),mers(dd),val5(dd)
	  write( 4321,spwc ) plne(dd),mers(dd),val6(dd)
	  write( 4322,spwc ) plne(dd),mers(dd),val7(dd)
	  endif
	
	  if ( RPR .eq. 1 ) then     
	  write( 4420,spwb ) plne(dd),mers(dd),val8(dd)
	  endif
	 enddo
	  
	 if ( RPSF .eq. 1 ) then
	 write( 4120,* ) " "
	 endif
	
	 if ( RPMOF .eq. 1 ) then 
	 write( 4220,* ) " "
	 write( 4221,* ) " "
	 write( 4222,* ) " "
	 write( 4223,* ) " "
	 write( 4224,* ) " "
	 write( 4225,* ) " "
	 write( 4226,* ) " "
	 endif
	
	 if ( RPM .eq. 1 ) then
	 write( 4320,* ) " "
	 write( 4321,* ) " "
	 write( 4322,* ) " "
	 endif
	
	 if ( RPR .eq. 1 ) then
	 write( 4420,* ) " "
	 endif
	
	 do dd = 1,uu
	  if ( RPSF .eq. 1 ) then
	  write( 4120,spwa ) time(dd),mers(dd),val0(dd)
	  endif
 	
	  if ( RPMOF .eq. 1 ) then
	  write( 4220,spwb ) time(dd),mers(dd),val1(dd)
	  write( 4221,spwb ) time(dd),mers(dd),val2(dd)
	  write( 4222,spwb ) time(dd),mers(dd),val3(dd)
	  write( 4223,spwb ) time(dd),mers(dd),val4(dd)
	  write( 4224,spwb ) time(dd),mers(dd),val9(dd)
	  write( 4225,spwb ) time(dd),mers(dd),val10(dd)
	  write( 4226,spwb ) time(dd),mers(dd),val11(dd)
	  endif
	
	  if ( RPM .eq. 1 ) then    
	  write( 4320,spwc ) time(dd),mers(dd),val5(dd)
	  write( 4321,spwc ) time(dd),mers(dd),val6(dd)
	  write( 4322,spwc ) time(dd),mers(dd),val7(dd)
	  endif
	
	  if ( RPR .eq. 1 ) then
	  write( 4420,spwb ) time(dd),mers(dd),val8(dd)
	  endif
	 enddo
	
	 if ( RPSF .eq. 1 ) then
	 write( 4120,* ) " "
	 endif
	
	 if ( RPMOF .eq. 1 ) then 
	 write( 4220,* ) " "
	 write( 4221,* ) " "
	 write( 4222,* ) " "
	 write( 4223,* ) " "
	 write( 4224,* ) " "
	 write( 4225,* ) " "
	 write( 4226,* ) " "
	 endif
	
	 if ( RPM .eq. 1 ) then
	 write( 4320,* ) " "
	 write( 4321,* ) " "
	 write( 4322,* ) " "
	 endif
	
	 if ( RPR .eq. 1 ) then
	 write( 4420,* ) " "
	 endif
	
	 if ( eek .eq. ffmmf ) then
	  do dd = 1,uu
	   if ( RPSF .eq. 1 ) then
	   write( 4120,spwa ) time(dd)+yy,mers(dd),val0(dd)
	   endif   
	
	   if ( RPMOF .eq. 1 ) then
	   write( 4220,spwb ) time(dd)+yy,mers(dd),val1(dd)
	   write( 4221,spwb ) time(dd)+yy,mers(dd),val2(dd)
	   write( 4222,spwb ) time(dd)+yy,mers(dd),val3(dd)
	   write( 4223,spwb ) time(dd)+yy,mers(dd),val4(dd)
	   write( 4224,spwb ) time(dd)+yy,mers(dd),val9(dd)
	   write( 4225,spwb ) time(dd)+yy,mers(dd),val10(dd)
	   write( 4226,spwb ) time(dd)+yy,mers(dd),val11(dd)
	   endif
	 
	   if ( RPM .eq. 1 ) then    
	   write( 4320,spwc ) time(dd)+yy,mers(dd),val5(dd)
	   write( 4321,spwc ) time(dd)+yy,mers(dd),val6(dd)
	   write( 4322,spwc ) time(dd)+yy,mers(dd),val7(dd)
	   endif
	 
	   if ( RPR .eq. 1 ) then
	   write( 4420,spwb ) time(dd)+yy,mers(dd),val8(dd)
	   endif
	  enddo
	 endif
	
	enddo

!-------VIII. GENERATING GNU FILES TO PLOT REPORTS

!	    write(*,*) "####################################"
!	    write(*,*) "#                                  #"
!	    write(*,*) "#       GENERATING GNU FILES       #"
!	    write(*,*) "#                                  #"
!	    write(*,*) "####################################"
      
                
!-------VIII.A.1. SAVING IMPORTANT DETAILS

	read( 10,* ) 
	read( 10,* ) 
	do np = 1,5
	 read( 10,* ) ts , tc
	 gt(np)=ts
	 le(np)=tc
	 do nth = 1,le(np)
	  read( 10,* ) mim,mfm
	  gmin( np,nth ) = mim
	  gmax( np,nth ) = mfm
	 enddo
	 read ( 10,*) 
	enddo

!-------VIII.A.2 DETERMINE INVOLVED MOLECULES

	l=0
	mq=0
	do idm = 1,2
	 do ppi = 1,pop
	  read(5,*) qb
	
	  if ((qb .eq. "SOL") .and. (l .ne. 4)) then
	   molty(ppi)=1
	   l=4
	   mq=mq+1
	   nam(idm)="SOL"
	   sub(idm)="{water}"
	   col(idm)=2           !for radial density profile
	   sam(idm)="water"     !for radial density profile
	   clr(idm)="'#1261A0'"
	   fmol(idm)=4220       !for mole fraction
	   col2(idm)=6
	   col3(idm)=7
	   EXIT
	
	  elseif ((qb .eq. "NON") .and. (l .ne. 9)) then
	   molty(ppi)=2
	   l=9
	   mq=mq+1
	   nam(idm)="NON"
	   sub(idm)="{/:Bold {/:Italic n}-nonane}"
	   col(idm)=3
	   sam(idm)="{/:Bold {/:Italic n}-nonane}"
	   clr(idm)="'#3BB143'"
	   fmol(idm)=4221
	   col2(idm)=8
	   col3(idm)=9
	   EXIT
	
	  elseif ((qb .eq. "BUT") .and. (l .ne. 6)) then
	   molty(ppi)=3
	   l=6
	   mq=mq+1
	   nam(idm)="BUT"
	   sub(idm)="{1-butanol}"
	   col(idm)=4
	   sam(idm)="1-butanol"
	   clr(idm)="'#FEDC56'"
	   fmol(idm)=4222
	   col2(idm)=10
	   col3(idm)=11
	   EXIT
	
	  elseif ((qb .eq. "NH3") .and. (l .ne. 5)) then
	   molty(ppi)=4
	   l=5
	   mq=mq+1
	   nam(idm)="AMM"
	   sub(idm)="{ammonia}"
	   col(idm)=5
	   sam(idm)="ammonia"
	   clr(idm)="'#DB4E4E'"
	   fmol(idm)=4223
	   col2(idm)=12
	   col3(idm)=13
	   EXIT

	  elseif ((qb .eq. "MET") .and. (l .ne. 3)) then
	   molty(ppi)=5
	   l=3
	   mq=mq+1
	   nam(idm)="MET"
	   sub(idm)="{methanol}"
	   col(idm)=6
	   sam(idm)="methanol"
	   clr(idm)="'#DF711B'"
	   fmol(idm)=4224
	   col2(idm)=14
	   col3(idm)=15
	   EXIT
	
	  elseif ((qb .eq. "ACT") .and. (l .ne. 5)) then
	   molty(ppi)=6
	   l=5
	   mq=mq+1
	   nam(idm)="ACT"
	   sub(idm)="{acetic}"
	   col(idm)=7
	   sam(idm)="acetic"
	   clr(idm)="'#A73489'"
	   fmol(idm)=4225
	   col2(idm)=16
	   col3(idm)=17
	   EXIT

	  elseif ((qb .eq. "OCT") .and. (l .ne. 10)) then
	   molty(ppi)=8
	   l=10
	   mq=mq+1
	   nam(idm)="OCT"
	   sub(idm)="{1-octanol}"
	   col(idm)=8
	   sam(idm)="1-octanol"
	   clr(idm)="'#A73489'"
	   fmol(idm)=4226
	   col2(idm)=18
	   col3(idm)=19
	   EXIT

	  endif
	 enddo
	
	 if ( mq .eq. 2 ) then           !Delete when necessary
	  if ( (nam(1) .eq. "AMM") .or. (nam(2) .eq. "AMM") ) then
	   rdpxrange   = "set xrange  [0:5]                       "
	   rdpxtics    = "set xtics  0,1,5                        "
	   freyrange   = "set yrange  [1:30]   noreverse writeback"
	   freytics    = "set ytics  (1,6,12,18,24,30)            "
	   mascbrange  = "set cbrange [0:200]  noreverse writeback"
	   mascbtics   = "set cbtics 0,40,200                     "
	   radcbrange  = "set cbrange [0:5]    noreverse writeback"
	
	   genylabelof = "set ylabel  offset -1.6,0               "
	   genclabelof = "set cblabel offset  1.2,0               "
	   genxrange   = "set xrange  [0:5]    noreverse writeback"
	   genyrange   = "set yrange  [0:30]   noreverse writeback"
	   genxtics    = "set xtics  0,1,5                        "
	   genytics    = "set ytics  0,6,30                       "
	
	  else
	   rdpxrange   = "set xrange  [0:10]   noreverse writeback"
	   rdpxtics    = "set xtics  0,2,10                       "
	   freyrange   = "set yrange  [5:100]  noreverse writeback"
	   freytics    = "set ytics  (5,20,40,60,80,100)          "
	   mascbrange  = "set cbrange [0:1250] noreverse writeback"
	   mascbtics   = "set cbtics 0,250,1250                   "
	   radcbrange  = "set cbrange [0:10]   noreverse writeback"
	
	   genylabelof = "set ylabel  offset -0.7,0               "
	   genclabelof = "set cblabel offset  2,0                 "
	   genxrange   = "set xrange  [0:50]   noreverse writeback"
	   genyrange   = "set yrange  [0:100]  noreverse writeback"
	   genxtics    = "set xtics  0,10,50                      "
	   genytics    = "set ytics  0,20,100                     "
	  endif
	  EXIT
	 endif
	enddo
	
	if ( col(2) .lt. col(1) ) then   !uniform tagging
	 temp1  = nam(1)                 !always WNBA order
	 nam(1) = nam(2)
	 nam(2) = temp1
	
	 temp2  = col(1)
	 col(1) = col(2)
	 col(2) = temp2
	
	 temp3  = sam(1)
	 sam(1) = sam(2)
	 sam(2) = temp3
	
	 temp4   = fmol(1)
	 fmol(1) = fmol(2)
	 fmol(2) = temp4
	
	 temp5  = sub(1)
	 sub(1) = sub(2)
	 sub(2) = temp5
	
	 temp6   = clr(1)
	 clr(1) = clr(2)
	 clr(2) = temp6
	
	 temp7   = col2(1)
	 col2(1) = col2(2)
	 col2(2) = temp7   
	
	 temp8   = col3(1)
	 col3(1) = col3(2)
	 col3(2) = temp8   
	endif

!-------VIII.B.1. RADIAL DENSITY PROFILE #1A - SPECIFYING PARAMETERS

	if ( RPRD1 .eq. 1 ) then          
	  sa01='(a2,a47,a4,a1,a3,a7)'
	  sa02='(a11,i4,a12,i9,a23,a28,a1,a3)'
	  sa04='(a12,a3,a1,a3,a7,f12.3,a7)'
	  sa05='(a11,i4,a42)'
	  sa06='(a28,a10,a5)'
 
!-------VIII.B.2. RADIAL DENSITY PROFILE #1A - GENERATE GNU FILE

	open(unit=4000,file='PLOTRDP1A.gnu')
	
   	write(4000,'(A)') "#!/usr/bin/gnuplot"
	write(4000,'(A)') " "
	write(4000, sa01) "# ",
     &                "GNUPLOT SETTINGS - RADIAL DENSITY PROFILE #1A -",
     &                nam(1),"_",nam(2),"SYSTEM"
	write(4000,'(A)') " "
	write(4000,'(A)') "# OUTPUT TYPE"
	write(4000,'(A)') " "
	write(4000,'(A)') "set encoding iso_8859_1"
	write(4000,'(A)') "set term postscript enhanced color portrait"
	write(4000,'(A)') " "
	write(4000,'(A)') "# PLOT FORMAT"
	write(4000,'(A)') " "
	write(4000,'(A)') "set bmargin 4"
	write(4000,'(A)') "set lmargin 9"
	write(4000,'(A)') "set border lw 2"
	write(4000,'(A)') "set size 1.1,0.6"
	write(4000,'(A)') " "
	write(4000,'(A)') "# PLOT AXIS & TICS"
	write(4000,'(A)') " "
	write(4000,'(A,X,A)') "set xlabel '{/:Bold radius", 
     &       "({/Helvetica=22 \305})}' font 'Helvetica Bold, 22'"
	write(4000,'(A,X,A)') "set ylabel '{/:Bold (10^{2})", 
     &        "{/:Italic n} molecules}' font 'Helvetica Bold, 22'"
	write(4000,'(A)') " "
	write(4000,'(A)') "set xlabel offset 0,-0.5"
	write(4000,'(A)') "set ylabel offset -0.1,0"
	write(4000,'(A)') " "
	write(4000,'(A)') "set xtic font 'Helvetica Bold, 20'"
	write(4000,'(A)') "set ytic font 'Helvetica Bold, 20'"
	write(4000,'(A)') " "
	write(4000,'(A)') "set xrange [0:600]"
	write(4000,'(A)') "set yrange [0:12]"
	write(4000,'(A)') " "
	write(4000,'(A)') "set xtics  0,150,600"
	write(4000,'(A)') "set ytics  0,3,12"
	write(4000,'(A)') "set mxtics 2"
	write(4000,'(A)') "set mytics 2"
	write(4000,'(A)') "set tics scale 2.2"  
	write(4000,'(A)') " "
	write(4000,'(A)') "# LEGEND KEY"
	write(4000,'(A)') " "
	write(4000,'(A)') "set key box lw 3 lc rgb '#808080'"
	write(4000,'(A)') "set key height 0.5"
	write(4000,'(A)') "set key width 0.01"
	write(4000,'(A)') "set key at graph 0.45,0.95"
	write(4000,'(A)') "set key font 'Helvetica Bold, 20'" 
	write(4000,'(A)') " "
	write(4000,'(A)') "# PLOT STYLE"
	write(4000,'(A)') " "
	write(4000, sa06) "set style line 1 lt 1 lc rgb",
     &                     clr(1),"lw 4"
	write(4000, sa06) "set style line 2 lt 1 lc rgb",
     &                     clr(2),"lw 4"
	write(4000,'(A)') "set style line 3 dt 3 lc rgb '#333333' lw 4"
	write(4000,'(A)') " "
	write(4000,'(A)') "# PLOT FILE"
	write(4000,'(A)') " "

	do np = 1,5
	  tim = gt(np)
 	  rmd = 3000
 	  rmc = rmd + np
	  write(4000,sa04) "set output '",nam(1),"_",nam(2),
     &                     "_RDP1A_",tim,"NS.eps'"
	  write(4000,sa02) "plot 'fort.",rmc, 
     &                     "' using 2:($",col2(1),
     &                     "/1000) w l ls 1 title '",sam(1),"'",
     &                     ", \"
	  write(4000,sa02) "'fort.",rmc,
     &                     "' using 2:($",col2(2),
     &                     "/1000) w l ls 2 title '",sam(2),"'",
     &                     ", \"
	  write(4000,sa05) "'fort.",rmc,
     &           "' using 2:($4/1000) w l ls 3 title 'total'"
	 write(4000,'(A)') " "
	enddo
	close(4000)

!-------VIII.C.1. RADIAL DENSITY PROFILE #1B - SPECIFYING PARAMETERS
          
	  sa01='(a2,a47,a4,a1,a3,a7)'
	  sa02='(a11,i4,a12,i9,a22,a28,a1,a3)'
	  sa04='(a12,a3,a1,a3,a7,f12.3,a7)'
	  sa05='(a11,i4,a41)'
	  sa06='(a28,a10,a5)'
 
!-------VIII.C.2. RADIAL DENSITY PROFILE #1B - GENERATE GNU FILE

	open(unit=4005,file='PLOTRDP1B.gnu')
	
   	write(4005,'(A)') "#!/usr/bin/gnuplot"
	write(4005,'(A)') " "
	write(4005, sa01) "# ",
     &                "GNUPLOT SETTINGS - RADIAL DENSITY PROFILE #1B -",
     &                nam(1),"_",nam(2),"SYSTEM"
	write(4005,'(A)') " "
	write(4005,'(A)') "# OUTPUT TYPE"
	write(4005,'(A)') " "
	write(4005,'(A)') "set encoding iso_8859_1"
	write(4005,'(A)') "set term postscript enhanced color portrait"
	write(4005,'(A)') " "
	write(4005,'(A)') "# PLOT FORMAT"
	write(4005,'(A)') " "
	write(4005,'(A)') "set bmargin 4"
	write(4005,'(A)') "set lmargin 9"
	write(4005,'(A)') "set border lw 2"
	write(4005,'(A)') "set size 1.1,0.6"
	write(4005,'(A)') " "
	write(4005,'(A)') "# PLOT AXIS & TICS"
	write(4005,'(A)') " "
	write(4005,'(A,X,A)') "set xlabel '{/:Bold radius", 
     &      "({/Helvetica=22 \305})}' font 'Helvetica Bold, 22'"
	write(4005,'(A,X,A)') "set ylabel '{/:Bold density (10^{-2}", 
     &    "{/Helvetica=22\305}^{-3})}' font 'Helvetica Bold, 22'"
	write(4005,'(A)') " "
	write(4005,'(A)') "set xlabel offset 0,-0.5"
	write(4005,'(A)') "set ylabel offset -0.1,0"
	write(4005,'(A)') " "
	write(4005,'(A)') "set xtic font 'Helvetica Bold, 20'"
	write(4005,'(A)') "set ytic font 'Helvetica Bold, 20'"
	write(4005,'(A)') " "
	write(4005,'(A)') "set xrange [0:600]"  !TO CHANGE
	write(4005,'(A)') "set yrange  [0:8]"
	write(4005,'(A)') " "
	write(4005,'(A)') "set xtics  0,150,600"
	write(4005,'(A)') "set ytics  0,2,8"
	write(4005,'(A)') "set mxtics 2"
	write(4005,'(A)') "set mytics 2"
	write(4005,'(A)') "set tics scale 2.2"  
	write(4005,'(A)') " "
	write(4005,'(A)') "# LEGEND KEY"
	write(4005,'(A)') " "
	write(4005,'(A)') "set key box lw 3 lc rgb '#808080'"
	write(4005,'(A)') "set key height 0.5"
	write(4005,'(A)') "set key width 0.01"
	write(4005,'(A)') "set key at graph 0.96,0.95"
	write(4005,'(A)') "set key font 'Helvetica Bold, 20'" 
	write(4005,'(A)') " "
	write(4005,'(A)') "# PLOT STYLE"
	write(4005,'(A)') " "
	write(4005, sa06) "set style line 1 lt 1 lc rgb",
     &                    clr(1),"lw 4"
	write(4005, sa06) "set style line 2 lt 1 lc rgb",
     &                    clr(2),"lw 4"
	write(4005,'(A)') "set style line 3 dt 3 lc rgb '#333333' lw 4"
	write(4005,'(A)') " "
	write(4005,'(A)') "# PLOT FILE"
	write(4005,'(A)') " "

	do np = 1,5
	  tim = gt(np)
 	  rmd = 3000
 	  rmc = rmd + np
	  write(4005,sa04) "set output '",nam(1),"_",nam(2),
     &                     "_RDP1B_",tim,"NS.eps'"
	  write(4005,sa02) "plot 'fort.",rmc, 
     &                     "' using 2:($",col3(1),
     &                     "*100) w l ls 1 title '",sam(1),"'",
     &                     ", \"
	  write(4005,sa02) "'fort.",rmc,
     &                     "' using 2:($",col3(2),
     &                     "*100) w l ls 2 title '",sam(2),"'",
     &                     ", \"
	  write(4005,sa05) "'fort.",rmc,
     &            "' using 2:($5*100) w l ls 3 title 'total'"
	 write(4005,'(A)') " "
	enddo
	close(4005)
	endif

!-------VIII.D.1. RADIAL DENSITY PROFILE #2A - SPECIFYING PARAMETERS
          
	if ( RPRD2 .eq. 1 ) then
	  sa01='(a2,a47,a4,a1,a3,a7)'
	  sa02='(a11,i4,a12,i9,a23,a28,a1,a3)'
	  saR4='(a12,a3,a1,a3,a7,f12.3,a3,i11,a1,i11,a8)'
	  sa05='(a11,i4,a42)'
	  sa06='(a28,a10,a5)'

!-------VIII.D.2. RADIAL DENSITY PROFILE #2A - GENERATE GNU FILE

	open(unit=4010,file='PLOTRDP2A.gnu')
	
   	write(4010,'(A)') "#!/usr/bin/gnuplot"
	write(4010,'(A)') " "
	write(4010, sa01) "# ",
     &                "GNUPLOT SETTINGS - RADIAL DENSITY PROFILE #2A -",
     &                nam(1),"_",nam(2),"SYSTEM"
	write(4010,'(A)') " "
	write(4010,'(A)') "# OUTPUT TYPE"
	write(4010,'(A)') " "
	write(4010,'(A)') "set encoding iso_8859_1"
	write(4010,'(A)') "set term postscript enhanced color portrait"
	write(4010,'(A)') " "
	write(4010,'(A)') "# PLOT FORMAT"
	write(4010,'(A)') " "
	write(4010,'(A)') "set bmargin 4"
	write(4010,'(A)') "set lmargin 9"
	write(4010,'(A)') "set border lw 2"
	write(4010,'(A)') "set size 1.1,0.6"
	write(4010,'(A)') " "
	write(4010,'(A)') "# PLOT AXIS & TICS"
	write(4010,'(A)') " "
	write(4010,'(A,X,A)') "set xlabel '{/:Bold radius", 
     &       "({/Helvetica=22 \305})}' font 'Helvetica Bold, 22'"
	write(4010,'(A,X,A)') "set ylabel '{/:Bold (10^{2})", 
     &        "{/:Italic n} molecules}' font 'Helvetica Bold, 22'"
	write(4010,'(A)') " "
	write(4010,'(A)') "set xlabel offset 0,-0.5"
	write(4010,'(A)') "set ylabel offset -0.1,0"
	write(4010,'(A)') " "
	write(4010,'(A)') "set xtic font 'Helvetica Bold, 20'"
	write(4010,'(A)') "set ytic font 'Helvetica Bold, 20'"
	write(4010,'(A)') " "
	write(4010,'(A)') "set xrange [0:90]"
	write(4010,'(A)') "set yrange [0:12]"
	write(4010,'(A)') " "
	write(4010,'(A)') "set xtics  0,18,90"
	write(4010,'(A)') "set ytics  0,3,12"
	write(4010,'(A)') "set mxtics 2"
	write(4010,'(A)') "set mytics 2"
	write(4010,'(A)') "set tics scale 2.2"  
	write(4010,'(A)') " "
	write(4010,'(A)') "# LEGEND KEY"
	write(4010,'(A)') " "
	write(4010,'(A)') "set key box lw 3 lc rgb '#808080'"
	write(4010,'(A)') "set key height 0.5"
	write(4010,'(A)') "set key width 0.01"
	write(4010,'(A)') "set key at graph 0.45,0.95"
	write(4010,'(A)') "set key font 'Helvetica Bold, 20'" 
	write(4010,'(A)') " "
	write(4010,'(A)') "# PLOT STYLE"
	write(4010,'(A)') " "
	write(4010, sa06) "set style line 1 lt 1 lc rgb",
     &                     clr(1),"lw 4"
	write(4010, sa06) "set style line 2 lt 1 lc rgb",
     &                     clr(2),"lw 4"
	write(4010,'(A)') "set style line 3 dt 3 lc rgb '#333333' lw 4"
	write(4010,'(A)') " "
	write(4010,'(A)') "# PLOT FILE"
	write(4010,'(A)') " "
	
	do np = 1,5
	 do nth = 1,le(np)
	  nin = gmin(np,nth)
	  nfn = gmax(np,nth)
	  tim = gt(np)
 	  rmd = 3006
 	  mxv = np*3
 	  rmc = rmd + mxv + nth
	  write(4010,saR4) "set output '",nam(1),"_",nam(2),
     &                     "_RDP2A_",tim,"NS_",nin,"-",nfn,"MER.eps'"
	  write(4010,sa02) "plot 'fort.",rmc, 
     &                     "' using 2:($",col2(1),
     &                     "/1000) w l ls 1 title '",sam(1),"'",
     &                     ", \"
	  write(4010,sa02) "'fort.",rmc,
     &                     "' using 2:($",col2(2),
     &                     "/1000) w l ls 2 title '",sam(2),"'",
     &                     ", \"
	  write(4010,sa05) "'fort.",rmc,
     &            "' using 2:($4/1000) w l ls 3 title 'total'"
	 enddo
	 write(4010,'(A)') " "
	enddo
	close(4010)

!-------VIII.E.1. RADIAL DENSITY PROFILE #2B - SPECIFYING PARAMETERS
          
	  sa01='(a2,a47,a4,a1,a3,a7)'
	  sa02='(a11,i4,a12,i9,a22,a28,a1,a3)'
	  saR4='(a12,a3,a1,a3,a7,f12.3,a3,i11,a1,i11,a8)'
	  sa05='(a11,i4,a41)'
	  sa06='(a28,a10,a5)'

!-------VIII.E.2. RADIAL DENSITY PROFILE #2B - GENERATE GNU FILE

	open(unit=4015,file='PLOTRDP2B.gnu')
	
   	write(4015,'(A)') "#!/usr/bin/gnuplot"
	write(4015,'(A)') " "
	write(4015, sa01) "# ",
     &                "GNUPLOT SETTINGS - RADIAL DENSITY PROFILE #2B -",
     &                nam(1),"_",nam(2),"SYSTEM"
	write(4015,'(A)') " "
	write(4015,'(A)') "# OUTPUT TYPE"
	write(4015,'(A)') " "
	write(4015,'(A)') "set encoding iso_8859_1"
	write(4015,'(A)') "set term postscript enhanced color portrait"
	write(4015,'(A)') " "
	write(4015,'(A)') "# PLOT FORMAT"
	write(4015,'(A)') " "
	write(4015,'(A)') "set bmargin 4"
	write(4015,'(A)') "set lmargin 9"
	write(4015,'(A)') "set border lw 2"
	write(4015,'(A)') "set size 1.1,0.6"
	write(4015,'(A)') " "
	write(4015,'(A)') "# PLOT AXIS & TICS"
	write(4015,'(A)') " "
	write(4015,'(A,X,A)') "set xlabel '{/:Bold radius", 
     &      "({/Helvetica=22 \305})}' font 'Helvetica Bold, 22'"
	write(4015,'(A,X,A)') "set ylabel '{/:Bold density (10^{-2}", 
     &    "{/Helvetica=22\305}^{-3})}' font 'Helvetica Bold, 22'"
	write(4015,'(A)') " "
	write(4015,'(A)') "set xlabel offset 0,-0.5"
	write(4015,'(A)') "set ylabel offset -0.1,0"
	write(4015,'(A)') " "
	write(4015,'(A)') "set xtic font 'Helvetica Bold, 20'"
	write(4015,'(A)') "set ytic font 'Helvetica Bold, 20'"
	write(4015,'(A)') " "
	write(4015,'(A)') "set xrange [0:90]"
	write(4015,'(A)') "set yrange  [0:8]"
	write(4015,'(A)') " "
	write(4015,'(A)') "set xtics 0,18,90"
	write(4015,'(A)') "set ytics 0,2,8"
	write(4015,'(A)') "set mxtics 2"
	write(4015,'(A)') "set mytics 2"
	write(4015,'(A)') "set tics scale 2.2"  
	write(4015,'(A)') " "
	write(4015,'(A)') "# LEGEND KEY"
	write(4015,'(A)') " "
	write(4015,'(A)') "set key box lw 3 lc rgb '#808080'"
	write(4015,'(A)') "set key height 0.5"
	write(4015,'(A)') "set key width 0.01"
	write(4015,'(A)') "set key at graph 0.96,0.95"
	write(4015,'(A)') "set key font 'Helvetica Bold, 20'" 
	write(4015,'(A)') " "
	write(4015,'(A)') "# PLOT STYLE"
	write(4015,'(A)') " "
	write(4015, sa06) "set style line 1 lt 1 lc rgb",
     &                     clr(1),"lw 4"
	write(4015, sa06) "set style line 2 lt 1 lc rgb",
     &                     clr(2),"lw 4"
	write(4015,'(A)') "set style line 3 dt 3 lc rgb '#333333' lw 4"
	write(4015,'(A)') " "
	write(4015,'(A)') "# PLOT FILE"
	write(4015,'(A)') " "
	
	do np = 1,5
	 do nth = 1,le(np)
	  nin = gmin(np,nth)
	  nfn = gmax(np,nth)
	  tim = gt(np)
 	  rmd = 3006
 	  mxv = np*3
 	  rmc = rmd + mxv + nth
	  write(4015,saR4) "set output '",nam(1),"_",nam(2),
     &                     "_RDP2B_",tim,"NS_",nin,"-",nfn,"MER.eps'"
	  write(4015,sa02) "plot 'fort.",rmc, 
     &                     "' using 2:($",col3(1),
     &                     "*100) w l ls 1 title '",sam(1),"'",
     &                     ", \"
	  write(4015,sa02) "'fort.",rmc,
     &                     "' using 2:($",col3(2),
     &                     "*100) w l ls 2 title '",sam(2),"'",
     &                     ", \"
	  write(4015,sa05) "'fort.",rmc,
     &            "' using 2:($5*100) w l ls 3 title 'total'"
	 enddo
	 write(4015,'(A)') " "
	enddo
	close(4015)
	endif

!-------VIII.F.1. RADIAL DENSITY PROFILE #3A - SPECIFYING PARAMETERS
          
	if ( RPRD3 .eq. 1 ) then
	  sa01='(a2,a47,a4,a1,a3,a7)'
	  sa02='(a11,i4,a12,i9,a23,a28,a1,a3)'
	  saR4='(a12,a3,a1,a3,a7,f12.3,a3,i11,a1,i11,a8)'
	  sa05='(a11,i4,a42)'
	  sa06='(a28,a10,a5)'

!-------VIII.F.2. RADIAL DENSITY PROFILE #3A - GENERATE GNU FILE

	open(unit=4020,file='PLOTRDP3A.gnu')
	
   	write(4020,'(A)') "#!/usr/bin/gnuplot"
	write(4020,'(A)') " "
	write(4020, sa01) "# ",
     &                "GNUPLOT SETTINGS - RADIAL DENSITY PROFILE #3A -",
     &                nam(1),"_",nam(2),"SYSTEM"
	write(4020,'(A)') " "
	write(4020,'(A)') "# OUTPUT TYPE"
	write(4020,'(A)') " "
	write(4020,'(A)') "set encoding iso_8859_1"
	write(4020,'(A)') "set term postscript enhanced color portrait"
	write(4020,'(A)') " "
	write(4020,'(A)') "# PLOT FORMAT"
	write(4020,'(A)') " "
	write(4020,'(A)') "set bmargin 4"
	write(4020,'(A)') "set lmargin 9"
	write(4020,'(A)') "set border lw 2"
	write(4020,'(A)') "set size 1.1,0.6"
	write(4020,'(A)') " "
	write(4020,'(A)') "# PLOT AXIS & TICS"
	write(4020,'(A)') " "
	write(4020,'(A,X,A)') "set xlabel '{/:Bold radius", 
     &       "({/Helvetica=22 \305})}' font 'Helvetica Bold, 22'"
	write(4020,'(A,X,A)') "set ylabel '{/:Bold (10^{2})", 
     &        "{/:Italic n} molecules}' font 'Helvetica Bold, 22'"
	write(4020,'(A)') " "
	write(4020,'(A)') "set xlabel offset 0,-0.5"
	write(4020,'(A)') "set ylabel offset -0.1,0"
	write(4020,'(A)') " "
	write(4020,'(A)') "set xtic font 'Helvetica Bold, 20'"
	write(4020,'(A)') "set ytic font 'Helvetica Bold, 20'"
	write(4020,'(A)') " "
	write(4020,'(A)') "set xrange [0:90]"
	write(4020,'(A)') "set yrange [0:12]"
	write(4020,'(A)') " "
	write(4020,'(A)') "set xtics  0,18,90"
	write(4020,'(A)') "set ytics  0,3,12"
	write(4020,'(A)') "set mxtics 2"
	write(4020,'(A)') "set mytics 2"
	write(4020,'(A)') "set tics scale 2.2"  
	write(4020,'(A)') " "
	write(4020,'(A)') "# LEGEND KEY"
	write(4020,'(A)') " "
	write(4020,'(A)') "set key box lw 3 lc rgb '#808080'"
	write(4020,'(A)') "set key height 0.5"
	write(4020,'(A)') "set key width 0.01"
	write(4020,'(A)') "set key at graph 0.45,0.95"
	write(4020,'(A)') "set key font 'Helvetica Bold, 20'" 
	write(4020,'(A)') " "
	write(4020,'(A)') "# PLOT STYLE"
	write(4020,'(A)') " "
	write(4020, sa06) "set style line 1 lt 1 lc rgb",
     &                     clr(1),"lw 4"
	write(4020, sa06) "set style line 2 lt 1 lc rgb",
     &                     clr(2),"lw 4"
	write(4020,'(A)') "set style line 3 dt 3 lc rgb '#333333' lw 4"
	write(4020,'(A)') " "
	write(4020,'(A)') "# PLOT FILE"
	write(4020,'(A)') " "
	
	do np = 1,5
	 do nth = 1,le(np)
	  nin = gmin(np,nth)
	  nfn = gmax(np,nth)
	  tim = gt(np)
 	  rmd = 3046
 	  mxv = np*3
 	  rmc = rmd + mxv + nth
	  write(4020,saR4) "set output '",nam(1),"_",nam(2),
     &                     "_RDP3A_",tim,"NS_",nin,"-",nfn,"MER.eps'"
	  write(4020,sa02) "plot 'fort.",rmc, 
     &                     "' using 2:($",col2(1),
     &                     "/1000) w l ls 1 title '",sam(1),"'",
     &                     ", \"
	  write(4020,sa02) "'fort.",rmc,
     &                     "' using 2:($",col2(2),
     &                     "/1000) w l ls 2 title '",sam(2),"'",
     &                     ", \"
	  write(4020,sa05) "'fort.",rmc,
     &            "' using 2:($4/1000) w l ls 3 title 'total'"
	 enddo
	 write(4020,'(A)') " "
	enddo
	close(4020)

!-------VIII.G.1. RADIAL DENSITY PROFILE #3B - SPECIFYING PARAMETERS
          
	  sa01='(a2,a47,a4,a1,a3,a7)'
	  sa02='(a11,i4,a12,i9,a22,a28,a1,a3)'
	  saR4='(a12,a3,a1,a3,a7,f12.3,a3,i11,a1,i11,a8)'
	  sa05='(a11,i4,a41)'
	  sa06='(a28,a10,a5)'

!-------VIII.G.2. RADIAL DENSITY PROFILE #3B - GENERATE GNU FILE

	open(unit=4025,file='PLOTRDP3B.gnu')
	
   	write(4025,'(A)') "#!/usr/bin/gnuplot"
	write(4025,'(A)') " "
	write(4025, sa01) "# ",
     &                "GNUPLOT SETTINGS - RADIAL DENSITY PROFILE #3B -",
     &                nam(1),"_",nam(2),"SYSTEM"
	write(4025,'(A)') " "
	write(4025,'(A)') "# OUTPUT TYPE"
	write(4025,'(A)') " "
	write(4025,'(A)') "set encoding iso_8859_1"
	write(4025,'(A)') "set term postscript enhanced color portrait"
	write(4025,'(A)') " "
	write(4025,'(A)') "# PLOT FORMAT"
	write(4025,'(A)') " "
	write(4025,'(A)') "set bmargin 4"
	write(4025,'(A)') "set lmargin 9"
	write(4025,'(A)') "set border lw 2"
	write(4025,'(A)') "set size 1.1,0.6"
	write(4025,'(A)') " "
	write(4025,'(A)') "# PLOT AXIS & TICS"
	write(4025,'(A)') " "
	write(4025,'(A,X,A)') "set xlabel '{/:Bold radius", 
     &      "({/Helvetica=22 \305})}' font 'Helvetica Bold, 22'"
	write(4025,'(A,X,A)') "set ylabel '{/:Bold density (10^{-2}", 
     &    "{/Helvetica=22\305}^{-3})}' font 'Helvetica Bold, 22'"
	write(4025,'(A)') " "
	write(4025,'(A)') "set xlabel offset 0,-0.5"
	write(4025,'(A)') "set ylabel offset -0.1,0"
	write(4025,'(A)') " "
	write(4025,'(A)') "set xtic font 'Helvetica Bold, 20'"
	write(4025,'(A)') "set ytic font 'Helvetica Bold, 20'"
	write(4025,'(A)') " "
	write(4025,'(A)') "set xrange [0:90]"
	write(4025,'(A)') "set yrange  [0:8]"
	write(4025,'(A)') " "
	write(4025,'(A)') "set xtics 0,18,90"
	write(4025,'(A)') "set ytics 0,2,8"
	write(4025,'(A)') "set mxtics 2"
	write(4025,'(A)') "set mytics 2"
	write(4025,'(A)') "set tics scale 2.2"  
	write(4025,'(A)') " "
	write(4025,'(A)') "# LEGEND KEY"
	write(4025,'(A)') " "
	write(4025,'(A)') "set key box lw 3 lc rgb '#808080'"
	write(4025,'(A)') "set key height 0.5"
	write(4025,'(A)') "set key width 0.01"
	write(4025,'(A)') "set key at graph 0.96,0.95"
	write(4025,'(A)') "set key font 'Helvetica Bold, 20'" 
	write(4025,'(A)') " "
	write(4025,'(A)') "# PLOT STYLE"
	write(4025,'(A)') " "
	write(4025, sa06) "set style line 1 lt 1 lc rgb",
     &                     clr(1),"lw 4"
	write(4025, sa06) "set style line 2 lt 1 lc rgb",
     &                     clr(2),"lw 4"
	write(4025,'(A)') "set style line 3 dt 3 lc rgb '#333333' lw 4"
	write(4025,'(A)') " "
	write(4025,'(A)') "# PLOT FILE"
	write(4025,'(A)') " "
	
	do np = 1,5
	 do nth = 1,le(np)
	  nin = gmin(np,nth)
	  nfn = gmax(np,nth)
	  tim = gt(np)
 	  rmd = 3046
 	  mxv = np*3
 	  rmc = rmd + mxv + nth
	  write(4025,saR4) "set output '",nam(1),"_",nam(2),
     &                     "_RDP3B_",tim,"NS_",nin,"-",nfn,"MER.eps'"
	  write(4025,sa02) "plot 'fort.",rmc, 
     &                     "' using 2:($",col3(1),
     &                     "*100) w l ls 1 title '",sam(1),"'",
     &                     ", \"
	  write(4025,sa02) "'fort.",rmc,
     &                     "' using 2:($",col3(2),
     &                     "*100) w l ls 2 title '",sam(2),"'",
     &                     ", \"
	  write(4025,sa05) "'fort.",rmc,
     &            "' using 2:($5*100) w l ls 3 title 'total'"
	 enddo
	 write(4025,'(A)') " "
	enddo
	close(4025)
	endif

!-------VIII.H.1. RADIAL DISTRIBUTION FUNCTION #1A - SPECIFYING PARAMETERS
          
	if ( RDF .eq. 1 ) then
	  saF1='(a1,a48,a4,a1,a3,a7)'
	  saF2='(a11,i4,a1,a9,i1,a17,a28,a1,a3)'
	  saF3='(a11,i4,a1,a9,i1,a17,a28,a1)'
	  saF4='(a12,a3,a1,a3,a5,f6.3,a3,i5,a1,i5,a8)'
	  saF6='(a28,a10,a5)'

	  sa01='(a2,a47,a4,a1,a3,a7)'
	  sa02='(a11,i4,a12,i9,a23,a28,a1,a3)'
	  saR4='(a12,a3,a1,a3,a7,f12.3,a3,i11,a1,i11,a8)'
	  sa05='(a11,i4,a42)'
	  sa06='(a28,a10,a10)'

!-------VIII.H.2. RADIAL DISTRIBUTION FUNCTION #1A - GENERATE GNU FILE

	open(unit=4050,file='PLOTRDF1A.gnu')
	
   	write(4050,'(A)') "#!/usr/bin/gnuplot"
	write(4050,'(A)') " "
	write(4050, saF1) "# ",
     &          "GNUPLOT SETTINGS - RADIAL DISTRIBUTION FUNCTION #1A -",
     &          nam(1),"_",nam(2),"SYSTEM"
	write(4050,'(A)') " "
	write(4050,'(A)') "# OUTPUT TYPE"
	write(4050,'(A)') " "
	write(4050,'(A)') "set encoding iso_8859_1"
	write(4050,'(A)') "set term postscript enhanced color portrait"
	write(4050,'(A)') " "
	write(4050,'(A)') "# PLOT FORMAT"
	write(4050,'(A)') " "
	write(4050,'(A)') "set bmargin 4"
	write(4050,'(A)') "set lmargin 9"
	write(4050,'(A)') "set border lw 2"
	write(4050,'(A)') "set size 1.1,0.6"
	write(4050,'(A)') " "
	write(4050,'(A)') "# PLOT AXIS & TICS"
	write(4050,'(A)') " "
	write(4050,'(A,X,A)') "set xlabel '{/:Bold radius", 
     &       "({/Helvetica=22 \305})}' font 'Helvetica Bold, 22'"
	write(4050,'(A,X,A)') "set ylabel '{/:Bold (10^{2})", 
     &        "{/:Italic n} molecules}' font 'Helvetica Bold, 22'"
	write(4050,'(A)') " "
	write(4050,'(A)') "set xlabel offset 0,-0.5"
	write(4050,'(A)') "set ylabel offset -0.1,0"
	write(4050,'(A)') " "
	write(4050,'(A)') "set xtic font 'Helvetica Bold, 20'"
	write(4050,'(A)') "set ytic font 'Helvetica Bold, 20'"
	write(4050,'(A)') " "
c	write(4050,'(A)') rdpxrange
	write(4050,'(A)') "set xrange  [0:90]"
	write(4050,'(A)') "set yrange  [0:12]"
	write(4050,'(A)') " "
c	write(4050,'(A)') rdpxtics
	write(4050,'(A)') "set xtics  0,18,90"
	write(4050,'(A)') "set ytics  0,3,12"
	write(4050,'(A)') "set mxtics 2"
	write(4050,'(A)') "set mytics 2"
	write(4050,'(A)') "set tics scale 2.2"  
	write(4050,'(A)') " "
	write(4050,'(A)') "# LEGEND KEY"
	write(4050,'(A)') " "
	write(4050,'(A)') "set key box lw 3 lc rgb '#808080'"
	write(4050,'(A)') "set key height 0.5"
	write(4050,'(A)') "set key width 0.01"
	write(4050,'(A)') "set key at graph 0.96,0.95"
	write(4050,'(A)') "set key font 'Helvetica Bold, 20'" 
	write(4050,'(A)') " "
	write(4050,'(A)') "# PLOT STYLE"
	write(4050,'(A)') " "
	write(4050, saF6) "set style line 1 lt 1 lc rgb",
     &                     clr(1),"lw 4"
	write(4050, saF6) "set style line 2 lt 1 lc rgb",
     &                     clr(2),"lw 4"
	write(4050,'(A)') "set style line 3 dt 3 lc rgb '#333333' lw 4"
	write(4050,'(A)') " "
	write(4050,'(A)') "# PLOT FILE"
	write(4050,'(A)') " "
	
	do np = 1,5
	 do nth = 1,le(np)
	  nin = gmin(np,nth)
	  nfn = gmax(np,nth)
	  tim = gt(np)
 	  rmd = 3066
 	  mxv = np*3
 	  rmc = rmd + mxv + nth
	  write(4050,saR4) "set output '",nam(1),"_",nam(2),
     &                     "_RDF1A_",tim,"NS_",nin,"-",nfn,"MER.eps'"
	  write(4050,sa02) "plot 'fort.",rmc, 
     &                     "' using 2:($",col2(1),
     &                     "/1000) w l ls 1 title '",sam(1),"'",
     &                     ", \"
	  write(4050,sa02) "'fort.",rmc,
     &                     "' using 2:($",col2(2),
     &                     "/1000) w l ls 2 title '",sam(2),"'",
     &                     ", \"
	  write(4050,sa05) "'fort.",rmc,
     &            "' using 2:($4/1000) w l ls 3 title 'total'"
	 enddo
	 write(4050,'(A)') " "
	enddo
	close(4050)

!-------VIII.I.1. RADIAL DISTRIBUTION FUNCTION #1B - SPECIFYING PARAMETERS
          
	  saF1='(a1,a48,a4,a1,a3,a7)'
	  saF2='(a11,i4,a1,a9,i1,a17,a28,a1,a3)'
	  saF3='(a11,i4,a1,a9,i1,a17,a28,a1)'
	  saF4='(a12,a3,a1,a3,a5,f6.3,a3,i5,a1,i5,a8)'
	  saF6='(a28,a10,a5)'

	  sa01='(a2,a47,a4,a1,a3,a7)'
	  sa02='(a11,i4,a12,i9,a22,a28,a1,a3)'
	  saR4='(a12,a3,a1,a3,a7,f12.3,a3,i11,a1,i11,a8)'
	  sa05='(a11,i4,a41)'
	  sa06='(a28,a10,a10)'

!-------VIII.I.2. RADIAL DISTRIBUTION FUNCTION #1B - GENERATE GNU FILE

	open(unit=4055,file='PLOTRDF1B.gnu')
	
   	write(4055,'(A)') "#!/usr/bin/gnuplot"
	write(4055,'(A)') " "
	write(4055, saF1) "# ",
     &          "GNUPLOT SETTINGS - RADIAL DISTRIBUTION FUNCTION #1B -",
     &          nam(1),"_",nam(2),"SYSTEM"
	write(4055,'(A)') " "
	write(4055,'(A)') "# OUTPUT TYPE"
	write(4055,'(A)') " "
	write(4055,'(A)') "set encoding iso_8859_1"
	write(4055,'(A)') "set term postscript enhanced color portrait"
	write(4055,'(A)') " "
	write(4055,'(A)') "# PLOT FORMAT"
	write(4055,'(A)') " "
	write(4055,'(A)') "set bmargin 4"
	write(4055,'(A)') "set lmargin 9"
	write(4055,'(A)') "set border lw 2"
	write(4055,'(A)') "set size 1.1,0.6"
	write(4055,'(A)') " "
	write(4055,'(A)') "# PLOT AXIS & TICS"
	write(4055,'(A)') " "
	write(4055,'(A,X,A)') "set xlabel '{/:Bold radius", 
     &      "({/Helvetica=22 \305})}' font 'Helvetica Bold, 22'"
	write(4055,'(A,X,A)') "set ylabel 'g(a)'", 
     &                        "font 'Helvetica Bold, 22'"
	write(4055,'(A)') " "
	write(4055,'(A)') "set xlabel offset 0,-0.5"
	write(4055,'(A)') "set ylabel offset -0.1,0"
	write(4055,'(A)') " "
	write(4055,'(A)') "set xtic font 'Helvetica Bold, 20'"
	write(4055,'(A)') "set ytic font 'Helvetica Bold, 20'"
	write(4055,'(A)') " "
c	write(4055,'(A)') rdpxrange
	write(4055,'(A)') "set xrange  [0:90]"
	write(4055,'(A)') "set yrange  [0:8]"
	write(4055,'(A)') " "
c	write(4055,'(A)') rdpxtics
	write(4055,'(A)') "set xtics  0,18,90"
	write(4055,'(A)') "set ytics  0,2,8"
	write(4055,'(A)') "set mxtics 2"
	write(4055,'(A)') "set mytics 2"
	write(4055,'(A)') "set tics scale 2.2"  
	write(4055,'(A)') " "
	write(4055,'(A)') "# LEGEND KEY"
	write(4055,'(A)') " "
	write(4055,'(A)') "set key box lw 3 lc rgb '#808080'"
	write(4055,'(A)') "set key height 0.5"
	write(4055,'(A)') "set key width 0.01"
	write(4055,'(A)') "set key at graph 0.96,0.95"
	write(4055,'(A)') "set key font 'Helvetica Bold, 20'" 
	write(4055,'(A)') " "
	write(4055,'(A)') "# PLOT STYLE"
	write(4055,'(A)') " "
	write(4055, saF6) "set style line 1 lt 1 lc rgb",
     &                     clr(1),"lw 4"
	write(4055, saF6) "set style line 2 lt 1 lc rgb",
     &                     clr(2),"lw 4"
	write(4055,'(A)') "set style line 3 dt 3 lc rgb '#333333' lw 4"
	write(4055,'(A)') " "
	write(4055,'(A)') "# PLOT FILE"
	write(4055,'(A)') " "
	
	do np = 1,5
	 do nth = 1,le(np)
	  nin = gmin(np,nth)
	  nfn = gmax(np,nth)
	  tim = gt(np)
 	  rmd = 3066
 	  mxv = np*3
 	  rmc = rmd + mxv + nth
	  write(4055,saR4) "set output '",nam(1),"_",nam(2),
     &                     "_RDF1B_",tim,"NS_",nin,"-",nfn,"MER.eps'"
	  write(4055,sa02) "plot 'fort.",rmc, 
     &                     "' using 2:($",col3(1),
     &                     "*100) w l ls 1 title '",sam(1),"'",
     &                     ", \"
	  write(4055,sa02) "'fort.",rmc,
     &                     "' using 2:($",col3(2),
     &                     "*100) w l ls 2 title '",sam(2),"'",
     &                     ", \"
	  write(4055,sa05) "'fort.",rmc,
     &            "' using 2:($5*100) w l ls 3 title 'total'"
	 enddo
	 write(4055,'(A)') " "
	enddo
	close(4055)
	endif

!-------VIII.J.1. CLUSTER SIZE FREQUENCY - SPECIFYING PARAMETERS
          
 	if (RPSF .eq. 1 ) then
	  sa11='(a1,a44,a4,a1,a3,a7)'
	  sa12='(a12,a3,a1,a3,a15)'

!-------VIII.J.2. CLUSTER SIZE FREQUENCY - GENERATE GNU FILE

 	open(unit=4100,file='PLOTfrequency.gnu')
 	
   	write(4100,'(A)') "#!/usr/bin/gnuplot"
	write(4100,'(A)') " "
	write(4100, sa11) "# ",
     &                "GNUPLOT SETTINGS - CLUSTER SIZE FREQUENCY -",
     &                nam(1),"_",nam(2),"SYSTEM"
	write(4100,'(A)') " "
	write(4100,'(A)') "# OUTPUT TYPE"
	write(4100,'(A)') " "
	write(4100,'(A)') "set term postscript enhanced portrait"
	write(4100,'(A)') " "
	write(4100,'(A)') "# PLOT FORMAT"
	write(4100,'(A)') " "
	write(4100,'(A)') "unset key"
	write(4100,'(A)') "set view map"
	write(4100,'(A)') "set size square"
	write(4100,'(A)') "set size 1.01,0.6"
	write(4100,'(A)') "set lmargin at screen 0"
	write(4100,'(A)') "set border lw 3"
	write(4100,'(A)') " "
	write(4100,'(A)') "# PLOT AXIS & TICS"
	write(4100,'(A)') " "
	write(4100,'(A,X,A)') "set xlabel 'Time (ns)'",
     &                        "font 'Helvetica Bold, 22'"
	write(4100,'(A,X,A)') "set ylabel 'Size (10^2)'",
     &                        "font 'Helvetica Bold, 22'"
	write(4100,'(A,X,A)') "set cblabel 'Frequency'",
     &                        "font 'Helvetica Bold, 22'"
	write(4100,'(A)') " "
	write(4100,'(A)') "set xtic  font 'Helvetica Bold, 20'"
	write(4100,'(A)') "set ytic  font 'Helvetica Bold, 20'"
	write(4100,'(A)') "set cbtic font 'Helvetica Bold, 20'"
	write(4100,'(A)') " "
	write(4100,'(A)') "set xlabel  offset  0,-0.3"
	write(4100,'(A)') genylabelof
	write(4100,'(A)') genclabelof
	write(4100,'(A)') " "
	write(4100,'(A)') genxrange
	write(4100,'(A)') freyrange
	write(4100,'(A)') "set cbrange [0:25]   noreverse writeback"
	write(4100,'(A)') " "
	write(4100,'(A)') genxtics
	write(4100,'(A)') freytics
	write(4100,'(A)') "set mxtics 2"
	write(4100,'(A)') "set mytics 2"
	write(4100,'(A)') "set tics scale 1"  
	write(4100,'(A)') " "
	write(4100,'(A)') "set xtics  out nomirror offset -0.2,0.4"
	write(4100,'(A)') "set ytics  out nomirror offset 0.6,0"
	write(4100,'(A)') "set cbtics offset -0.6,0"
	write(4100,'(A)') " "
	write(4100,'(A)') "set grid xtics lc rgb '#bbbbbb' lw 1 lt 0"
	write(4100,'(A)') "set grid ytics lc rgb '#bbbbbb' lw 1 lt 0"
	write(4100,'(A)') " "
	write(4100,'(A,X,A,X,A,X,A,X,A)') "set palette defined", 
     &                 "(0 '#5e4fa2', 10 '#3288bd', 20 '#66c2a5',", 
     &                 "30 '#abdda4', 40 '#e6f598', 50 '#ffffbf',", 
     &                 "60 '#fee08b', 70 '#fdae61', 80 '#f46d43',", 
     &                 "90 '#d53e4f', 100 '#9e0142', 100.1 'dark-grey')"
	write(4100,'(A)') " "
	write(4100,'(A)') "# PLOT FILE"
	write(4100,'(A)') " "
	write(4100,sa12)"set output '",nam(1),"_",nam(2),"_frequency.eps'"
	write(4100,'(A)') "splot 'fort.4120' w pm3d"
	close(4100)
	endif

!-------VIII.K.1. MOLE FRACTION - SPECIFYING PARAMETERS
        
	if ( RPMOF .eq. 1 ) then
	  sa21='(a1,a43,a4,a1,a3,a7)'
	  sa22='(a15,a28,a27)'
	  sa23='(a12,a3,a1,a3,a2,a3,a17)'
	  sa24='(a12,i4,a8)'

!-------VIII.K.2. MOLE FRACTION - GENERATE GNU FILE

 	open(unit=4200,file='PLOTmolfraction.gnu')
 	
   	write(4200,'(A)') "#!/usr/bin/gnuplot"
	write(4200,'(A)') " "
	write(4200, sa21) "# ",             
     &                "GNUPLOT SETTINGS - CLUSTER MOLE FRACTION -",
     &                nam(1),"_",nam(2),"SYSTEM"
	write(4200,'(A)') " "
	write(4200,'(A)') "# OUTPUT TYPE"
	write(4200,'(A)') " "
	write(4200,'(A)') "set term postscript enhanced portrait"
	write(4200,'(A)') " "
	write(4200,'(A)') "# PLOT FORMAT"
	write(4200,'(A)') " "
	write(4200,'(A)') "unset key"
	write(4200,'(A)') "set view map"
	write(4200,'(A)') "set size square"
	write(4200,'(A)') "set size 1.01,0.6"
	write(4200,'(A)') "set lmargin at screen 0"
	write(4200,'(A)') "set border lw 3"
	write(4200,'(A)') " "
	write(4200,'(A)') "# PLOT AXIS & TICS"
	write(4200,'(A)') " "
	write(4200,'(A,X,A)') "set xlabel 'Time (ns)'",
     &                        "font 'Helvetica Bold, 22'"
	write(4200,'(A,X,A)') "set ylabel 'Size (10^2)'",
     &                        "font 'Helvetica Bold, 22'"
	write(4200, sa22) "set cblabel 'X_",sub(1),
     &                        "' font 'Helvetica Bold, 22'"
	write(4200,'(A)') " "
	write(4200,'(A)') "set xtic  font 'Helvetica Bold, 20'"
	write(4200,'(A)') "set ytic  font 'Helvetica Bold, 20'"
	write(4200,'(A)') "set cbtic font 'Helvetica Bold, 20'"
	write(4200,'(A)') " "
	write(4200,'(A)') "set xlabel  offset  0,-0.3"
	write(4200,'(A)') genylabelof
	write(4200,'(A)') genclabelof
	write(4200,'(A)') " "
	write(4200,'(A)') genxrange
	write(4200,'(A)') genyrange
	write(4200,'(A)') "set cbrange [0: 1]   noreverse writeback"
	write(4200,'(A)') " "
	write(4200,'(A)') genxtics
	write(4200,'(A)') genytics
	write(4200,'(A)') "set mxtics 2"
	write(4200,'(A)') "set mytics 2"
	write(4200,'(A)') "set tics scale 1"  
	write(4200,'(A)') " "
	write(4200,'(A)') "set xtics  out nomirror offset -0.2,0.4"
	write(4200,'(A)') "set ytics  out nomirror offset 0.6,0"
	write(4200,'(A)') "set cbtics offset -0.6,0"
	write(4200,'(A)') " "
	write(4200,'(A)') "set grid xtics lc rgb '#bbbbbb' lw 1 lt 0"
	write(4200,'(A)') "set grid ytics lc rgb '#bbbbbb' lw 1 lt 0"
	write(4200,'(A)') " "
	write(4200,'(A,X,A,X,A,X,A,X,A)') "set palette defined", 
     &                 "(0 '#5e4fa2', 10 '#3288bd', 20 '#66c2a5',", 
     &                 "30 '#abdda4', 40 '#e6f598', 50 '#ffffbf',", 
     &                 "60 '#fee08b', 70 '#fdae61', 80 '#f46d43',", 
     &                 "90 '#d53e4f', 100 '#9e0142', 100.1 'dark-grey')"
	write(4200,'(A)') " "
	write(4200,'(A)') "# PLOT FILE"
	write(4200,'(A)') " "
	write(4200,sa23) "set output '",nam(1),"_",nam(2),"_X",
     &                    nam(1),"_molfraction.eps'"
	write(4200,sa24) "splot 'fort.",fmol(1),"' w pm3d"
	write(4200,'(A)') " "
	write(4200,sa22) "set cblabel 'X_",sub(2),
     &                        "' font 'Helvetica Bold, 22'"
	write(4200,'(A)') " "
	write(4200,sa23) "set output '",nam(1),"_",nam(2),"_X",
     &                    nam(2),"_molfraction.eps'"
	write(4200,sa24) "splot 'fort.",fmol(2),"' w pm3d"
	close(4200)
	endif

!-------VIII.L.1. CLUSTER MASS - SPECIFYING PARAMETERS
          
	if ( RPM .eq. 1 ) then
	  sa31='(a1,a34,a4,a1,a3,a7)'
	  sa32='(a12,a3,a1,a3,a10)'

!-------VIII.L.2. CLUSTER MASS - GENERATE GNU FILE

 	open(unit=4300,file='PLOTmass.gnu')
	
   	write(4300,'(A)') "#!/usr/bin/gnuplot"
	write(4300,'(A)') " "
	write(4300, sa31) "# ",
     &                "GNUPLOT SETTINGS - CLUSTER MASS -",
     &                nam(1),"_",nam(2),"SYSTEM"
	write(4300,'(A)') " "
	write(4300,'(A)') "# OUTPUT TYPE"
	write(4300,'(A)') " "
	write(4300,'(A)') "set term postscript enhanced portrait"
	write(4300,'(A)') " "
	write(4300,'(A)') "# PLOT FORMAT"
	write(4300,'(A)') " "
	write(4300,'(A)') "unset key"
	write(4300,'(A)') "set view map"
	write(4300,'(A)') "set size square"
	write(4300,'(A)') "set size 1.01,0.6"
	write(4300,'(A)') "set lmargin at screen 0"
	write(4300,'(A)') "set border lw 3"
	write(4300,'(A)') " "
	write(4300,'(A)') "# PLOT AXIS & TICS"
	write(4300,'(A)') " "
	write(4300,'(A,X,A)') "set xlabel 'Time (ns)'",
     &                        "font 'Helvetica Bold, 22'"
	write(4300,'(A,X,A)') "set ylabel 'Size (10^2)'",
     &                        "font 'Helvetica Bold, 22'"
	write(4300,'(A,X,A)') "set cblabel 'Mass (10^{-20} g)'",
     &                        "font 'Helvetica Bold, 22'"
	write(4300,'(A)') " "
	write(4300,'(A)') "set xtic  font 'Helvetica Bold, 20'"
	write(4300,'(A)') "set ytic  font 'Helvetica Bold, 20'"
	write(4300,'(A)') "set cbtic font 'Helvetica Bold, 20'"
	write(4300,'(A)') " "
	write(4300,'(A)') "set xlabel  offset  0,-0.3"
	write(4300,'(A)') genylabelof
	write(4300,'(A)') "set cblabel offset  2,0"
	write(4300,'(A)') " "
	write(4300,'(A)') genxrange
	write(4300,'(A)') genyrange
	write(4300,'(A)') mascbrange
	write(4300,'(A)') " "
	write(4300,'(A)') genxtics
	write(4300,'(A)') genytics
	write(4300,'(A)') mascbtics
	write(4300,'(A)') "set mxtics 2"
	write(4300,'(A)') "set mytics 2"
	write(4300,'(A)') "set tics scale 1"  
	write(4300,'(A)') " "
	write(4300,'(A)') "set xtics  out nomirror offset -0.2,0.4"
	write(4300,'(A)') "set ytics  out nomirror offset 0.6,0"
	write(4300,'(A)') "set cbtics offset -0.6,0"
	write(4300,'(A)') " "
	write(4300,'(A)') "set grid xtics lc rgb '#bbbbbb' lw 1 lt 0"
	write(4300,'(A)') "set grid ytics lc rgb '#bbbbbb' lw 1 lt 0"
	write(4300,'(A)') " "
	write(4300,'(A)') " "
	write(4300,'(A,X,A,X,A,X,A,X,A)') "set palette defined", 
     &                 "(0 '#5e4fa2', 10 '#3288bd', 20 '#66c2a5',", 
     &                 "30 '#abdda4', 40 '#e6f598', 50 '#ffffbf',", 
     &                 "60 '#fee08b', 70 '#fdae61', 80 '#f46d43',", 
     &                 "90 '#d53e4f', 100 '#9e0142', 100.1 'dark-grey')"
	write(4300,'(A)') " "
	write(4300,'(A)') "# PLOT FILE"
	write(4300,'(A)') " "
	write(4300,sa32)  "set output '",nam(1),"_",nam(2),"_mass.eps'"
	write(4300,'(A)') "splot 'fort.4320' w pm3d"
	close(4300)

!-------VIII.M.1. CLUSTER MASS UPPER LIMIT - SPECIFYING PARAMETERS
          
	  sa51='(a1,a45,a4,a1,a3,a7)'
	  sa52='(a12,a3,a1,a3,a17)'

!-------VIII.M.2. CLUSTER MASS UPPER LIMIT - GENERATE GNU FILE

 	open(unit=4301,file='PLOTmassfracmax.gnu')
	
   	write(4301,'(A)') "#!/usr/bin/gnuplot"
	write(4301,'(A)') " "
	write(4301, sa51) "# ",             
     &                "GNUPLOT SETTINGS - MASS FRACTION (G/MAX G) -",
     &                nam(1),"_",nam(2),"SYSTEM"
	write(4301,'(A)') " "
	write(4301,'(A)') "# OUTPUT TYPE"
	write(4301,'(A)') " "
	write(4301,'(A)') "set term postscript enhanced portrait"
	write(4301,'(A)') " "
	write(4301,'(A)') "# PLOT FORMAT"
	write(4301,'(A)') " "
	write(4301,'(A)') "unset key"
	write(4301,'(A)') "set view map"
	write(4301,'(A)') "set size square"
	write(4301,'(A)') "set size 1.01,0.6"
	write(4301,'(A)') "set lmargin at screen 0"
	write(4301,'(A)') "set border lw 3"
	write(4301,'(A)') " "
	write(4301,'(A)') "# PLOT AXIS & TICS"
	write(4301,'(A)') " "
	write(4301,'(A,X,A)') "set xlabel 'Time (ns)'",
     &                        "font 'Helvetica Bold, 22'"
	write(4301,'(A,X,A)') "set ylabel 'Size (10^2)'",
     &                        "font 'Helvetica Bold, 22'"
	write(4301,'(A,X,A)') "set cblabel 'Mass fraction (g/max g)'",
     &                        "font 'Helvetica Bold, 22'"
	write(4301,'(A)') " "
	write(4301,'(A)') "set xtic  font 'Helvetica Bold, 20'"
	write(4301,'(A)') "set ytic  font 'Helvetica Bold, 20'"
	write(4301,'(A)') "set cbtic font 'Helvetica Bold, 20'"
	write(4301,'(A)') " "
	write(4301,'(A)') "set xlabel  offset  0,-0.3"
	write(4301,'(A)') genylabelof
	write(4301,'(A)') genclabelof
	write(4301,'(A)') " "
	write(4301,'(A)') genxrange
	write(4301,'(A)') genyrange
	write(4301,'(A)') "set cbrange [0: 1]   noreverse writeback"
	write(4301,'(A)') " "
	write(4301,'(A)') genxtics
	write(4301,'(A)') genytics
	write(4301,'(A)') "set mxtics 2"
	write(4301,'(A)') "set mytics 2"
	write(4301,'(A)') "set tics scale 1"  
	write(4301,'(A)') " "
	write(4301,'(A)') "set xtics  out nomirror offset -0.2,0.4"
	write(4301,'(A)') "set ytics  out nomirror offset 0.6,0"
	write(4301,'(A)') "set cbtics offset -0.6,0"
	write(4301,'(A)') " "
	write(4301,'(A)') "set grid xtics lc rgb '#bbbbbb' lw 1 lt 0"
	write(4301,'(A)') "set grid ytics lc rgb '#bbbbbb' lw 1 lt 0"
	write(4301,'(A)') " "
	write(4301,'(A,X,A,X,A,X,A,X,A)') "set palette defined", 
     &                 "(0 '#5e4fa2', 10 '#3288bd', 20 '#66c2a5',", 
     &                 "30 '#abdda4', 40 '#e6f598', 50 '#ffffbf',", 
     &                 "60 '#fee08b', 70 '#fdae61', 80 '#f46d43',", 
     &                 "90 '#d53e4f', 100 '#9e0142', 100.1 'dark-grey')"
	write(4301,'(A)') " "
	write(4301,'(A)') "# PLOT FILE"
	write(4301,'(A)') " "
	write(4301,sa52)"set output '",nam(1),"_",nam(2),
     &                        "_massfracmax.eps'"
	write(4301,'(A)') "splot 'fort.4321' w pm3d"
	close(4301)

!-------VIII.N.1. CLUSTER MASS LOWER LIMIT - SPECIFYING PARAMETERS
          
	  sa61='(a1,a45,a4,a1,a3,a7)'
	  sa62='(a12,a3,a1,a3,a17)'

!-------VIII.N.2. CLUSTER MASS LOWER LIMIT - GENERATE GNU FILE

 	open(unit=4302,file='PLOTmassfracmin.gnu')
	
   	write(4302,'(A)') "#!/usr/bin/gnuplot"
	write(4302,'(A)') " "
	write(4302, sa61) "# ",             
     &                "GNUPLOT SETTINGS - MASS FRACTION (G/MIN G) -",
     &                nam(1),"_",nam(2),"SYSTEM"
	write(4302,'(A)') " "
	write(4302,'(A)') "# OUTPUT TYPE"
	write(4302,'(A)') " "
	write(4302,'(A)') "set term postscript enhanced portrait"
	write(4302,'(A)') " "
	write(4302,'(A)') "# PLOT FORMAT"
	write(4302,'(A)') " "
	write(4302,'(A)') "unset key"
	write(4302,'(A)') "set view map"
	write(4302,'(A)') "set size square"       
	write(4302,'(A)') "set size 1.01,0.6"                      
	write(4302,'(A)') "set lmargin at screen 0"                      
	write(4302,'(A)') "set border lw 3"
	write(4302,'(A)') " "
	write(4302,'(A)') "# PLOT AXIS & TICS"
	write(4302,'(A)') " "
	write(4302,'(A,X,A)') "set xlabel 'Time (ns)'",
     &                        "font 'Helvetica Bold, 22'"
	write(4302,'(A,X,A)') "set ylabel 'Size (10^2)'",
     &                        "font 'Helvetica Bold, 22'"
	write(4302,'(A,X,A)') "set cblabel 'Mass fraction (g/min g)'",
     &                        "font 'Helvetica Bold, 22'"
	write(4302,'(A)') " "
	write(4302,'(A)') "set xtic  font 'Helvetica Bold, 20'"
	write(4302,'(A)') "set ytic  font 'Helvetica Bold, 20'"
	write(4302,'(A)') "set cbtic font 'Helvetica Bold, 20'"
	write(4302,'(A)') " "
	write(4302,'(A)') "set xlabel  offset  0,-0.3"
	write(4302,'(A)') genylabelof
	write(4302,'(A)') genclabelof
	write(4302,'(A)') " "
	write(4302,'(A)') genxrange
	write(4302,'(A)') genyrange
	write(4302,'(A)') "set cbrange [0:10]   noreverse writeback"
	write(4302,'(A)') " "
	write(4302,'(A)') genxtics
	write(4302,'(A)') genytics
	write(4302,'(A)') "set mxtics 2"
	write(4302,'(A)') "set mytics 2"
	write(4302,'(A)') "set tics scale 1"
	write(4302,'(A)') " "
	write(4302,'(A)') "set xtics  out nomirror offset -0.2,0.4"
	write(4302,'(A)') "set ytics  out nomirror offset 0.6,0"
	write(4302,'(A)') "set cbtics offset -0.6,0"
	write(4302,'(A)') " "
	write(4302,'(A)') "set grid xtics lc rgb '#bbbbbb' lw 1 lt 0"
	write(4302,'(A)') "set grid ytics lc rgb '#bbbbbb' lw 1 lt 0"
	write(4302,'(A)') " "
	write(4302,'(A,X,A,X,A,X,A,X,A)') "set palette defined", 
     &                 "(0 '#5e4fa2', 10 '#3288bd', 20 '#66c2a5',", 
     &                 "30 '#abdda4', 40 '#e6f598', 50 '#ffffbf',", 
     &                 "60 '#fee08b', 70 '#fdae61', 80 '#f46d43',", 
     &                 "90 '#d53e4f', 100 '#9e0142', 100.1 'dark-grey')"
	write(4302,'(A)') " "
	write(4302,'(A)') "# PLOT FILE"
	write(4302,'(A)') " "
	write(4302,sa62)"set output '",nam(1),"_",nam(2),
     &                        "_massfracmin.eps'"
	write(4302,'(A)') "splot 'fort.4322' w pm3d"
	close(4302)
	endif

!-------VIII.O.1. CLUSTER RADIUS - SPECIFYING PARAMETERS
          
	if ( RPR .eq. 1 ) then
	  sa71='(a1,a36,a4,a1,a3,a7)'
	  sa72='(a12,a3,a1,a3,a12)'

!-------VIII.O.2. CLUSTER RADIUS - GENERATE GNU FILE

 	open(unit=4400,file='PLOTradius.gnu')
	
   	write(4400,'(A)') "#!/usr/bin/gnuplot"
	write(4400,'(A)') " "
	write(4400, sa71) "# ",             
     &                "GNUPLOT SETTINGS - CLUSTER RADIUS -",
     &                nam(1),"_",nam(2),"SYSTEM"
	write(4400,'(A)') " "
	write(4400,'(A)') "# OUTPUT TYPE"
	write(4400,'(A)') " "
	write(4400,'(A)') "set term postscript enhanced portrait"
	write(4400,'(A)') " "
	write(4400,'(A)') "# PLOT FORMAT"
	write(4400,'(A)') " "
	write(4400,'(A)') "unset key"
	write(4400,'(A)') "set view map"
	write(4400,'(A)') "set size square"
	write(4400,'(A)') "set size 1.01,0.6"
	write(4400,'(A)') "set lmargin at screen 0"
	write(4400,'(A)') "set border lw 3"
	write(4400,'(A)') " "
	write(4400,'(A)') "# PLOT AXIS & TICS"
	write(4400,'(A)') " "
	write(4400,'(A,X,A)') "set xlabel 'Time (ns)'",
     &                        "font 'Helvetica Bold, 22'"
	write(4400,'(A,X,A)') "set ylabel 'Size (10^2)'",
     &                        "font 'Helvetica Bold, 22'"
	write(4400,'(A,X,A)') "set cblabel 'Radius (nm)'",
     &                        "font 'Helvetica Bold, 22'"
	write(4400,'(A)') " "
	write(4400,'(A)') "set xtic  font 'Helvetica Bold, 20'"
	write(4400,'(A)') "set ytic  font 'Helvetica Bold, 20'"
	write(4400,'(A)') "set cbtic font 'Helvetica Bold, 20'"
	write(4400,'(A)') " "
	write(4400,'(A)') "set xlabel  offset  0,-0.3"
	write(4400,'(A)') genylabelof
	write(4400,'(A)') genclabelof
	write(4400,'(A)') " "
	write(4400,'(A)') genxrange
	write(4400,'(A)') genyrange
	write(4400,'(A)') radcbrange 
	write(4400,'(A)') " "                                       
	write(4400,'(A)') genxtics                                 
	write(4400,'(A)') genytics                              
	write(4400,'(A)') "set mxtics 2"
	write(4400,'(A)') "set mytics 2"                                      
	write(4400,'(A)') "set tics scale 1"                                 
	write(4400,'(A)') " "                                            
	write(4400,'(A)') "set xtics  out nomirror offset -0.2,0.4"          
	write(4400,'(A)') "set ytics  out nomirror offset 0.6,0"            
	write(4400,'(A)') "set cbtics offset -0.6,0"                         
	write(4400,'(A)') " "                                                  
	write(4400,'(A)') "set grid xtics lc rgb '#bbbbbb' lw 1 lt 0"
	write(4400,'(A)') "set grid ytics lc rgb '#bbbbbb' lw 1 lt 0"
	write(4400,'(A)') " "
	write(4400,'(A,X,A,X,A,X,A,X,A)') "set palette defined", 
     &                 "(0 '#5e4fa2', 10 '#3288bd', 20 '#66c2a5',", 
     &                 "30 '#abdda4', 40 '#e6f598', 50 '#ffffbf',", 
     &                 "60 '#fee08b', 70 '#fdae61', 80 '#f46d43',", 
     &                 "90 '#d53e4f', 100 '#9e0142', 100.1 'dark-grey')"
	write(4400,'(A)') " "
	write(4400,'(A)') "# PLOT FILE"
	write(4400,'(A)') " "
	write(4400,sa72)"set output '",nam(1),"_",nam(2),
     &                        "_radius.eps'"
	write(4400,'(A)') "splot 'fort.4420' w pm3d"
	close(4400)
	endif
	  

! ########################################################################################################

c	call system_clock (t2, clock_rate, clock_max)
c
c        SECONDS=real(t2-t1)/real(clock_rate)
c        write(*,*) " "
c        write(*,'(a21,i3,a9,f7.3,a10)')'      (TIME ELAPSED:',
c     &                          INT(SECONDS/60),'MINUTE/S',
c     &                          MOD(SECONDS,60d0),'SECOND/S)'

	end
